services:
  redis:
    container_name: redis
    image: redis
    environment:
      - REDIS_PORT=6379
    networks:
      - backend_network
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/data

networks:
  backend_network:
    driver: bridge

volumes:
  redis:
    driver: local
